variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - docker version
  - packer version

stages:
  - validate
  - baseimages
  - images
  - publish

validate:
  stage: validate
  tags:
    - packer
    - docker-host
  script:
    - find . -maxdepth 1 -name '*.json' -print0 | xargs -t0n1 packer validate

baseimage:bionic:
  stage: baseimages
  tags:
    - packer
    - docker-host
  script:
    - packer build $CI_PROJECT_DIR/baseimage-bionic.json

baseimage:publish:
  stage: baseimages
  only:
    - schedules
  tags:
    - packer
    - docker-host
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - docker tag mjonuschat/baseimage:latest mjonuschat/baseimage:bionic
    - docker tag mjonuschat/baseimage:latest mjonuschat/baseimage:bionic-$(date +%Y%m%d)
    - docker push mjonuschat/baseimage:latest
    - docker push mjonuschat/baseimage:bionic
    - docker push mjonuschat/baseimage:bionic-$(date +%Y%m%d)
  after_script:
    - docker logout

passenger:ruby24:
  stage: images
  tags:
    - packer
    - docker-host
  script:
    - packer build $CI_PROJECT_DIR/passenger-ruby24.json
  dependencies:
    - baseimage:bionic

passenger:ruby25:
  stage: images
  tags:
    - packer
    - docker-host
  script:
    - packer build $CI_PROJECT_DIR/passenger-ruby25.json
  dependencies:
    - baseimage:bionic

passenger:ruby26:
  stage: images
  tags:
    - packer
    - docker-host
  script:
    - packer build $CI_PROJECT_DIR/passenger-ruby26.json
  dependencies:
    - baseimage:bionic

passenger:publish:
  stage: publish
  only:
    - schedules
  tags:
    - packer
    - docker-host
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - docker tag mjonuschat/passenger-ruby24:latest mjonuschat/passenger-ruby24:$(jq -r .variables.ruby_version passenger-ruby24.json)
    - docker tag mjonuschat/passenger-ruby24:latest mjonuschat/passenger-ruby24:$(date +%Y%m%d)
    - docker tag mjonuschat/passenger-ruby24:latest mjonuschat/passenger-ruby25:$(jq -r .variables.ruby_version passenger-ruby25.json)
    - docker tag mjonuschat/passenger-ruby24:latest mjonuschat/passenger-ruby25:$(date +%Y%m%d)
    - docker tag mjonuschat/passenger-ruby24:latest mjonuschat/passenger-ruby26:$(jq -r .variables.ruby_version passenger-ruby26.json)
    - docker tag mjonuschat/passenger-ruby24:latest mjonuschat/passenger-ruby26:$(date +%Y%m%d)
    - docker push mjonuschat/passenger-ruby24:latest
    - docker push mjonuschat/passenger-ruby24:$(date +%Y%m%d)
    - docker push mjonuschat/passenger-ruby25:$(jq -r .variables.ruby_version passenger-ruby25.json)
    - docker push mjonuschat/passenger-ruby24:latest
    - docker push mjonuschat/passenger-ruby26:$(jq -r .variables.ruby_version passenger-ruby26.json)
    - docker push mjonuschat/passenger-ruby26:$(date +%Y%m%d)
  after_script:
    - docker rmi -f $(docker images | awk '/mjonuschat\// { print $1 ":" $2 }') || true
    - docker logout
    - docker system prune -f